### ISSUE TITLE
Django 1.7 AppConfig support

### ISSUE THREAD

**Issue by serathius** [miracle2k/django-assets#45]
Django 1.7 allows creation of AppConfigs for project apps, using them to register application in INSTALLED_APPS.
'django_app.apps.AppConfig' instead of 'django_app'

Loading apps in django-assets assumes that apps are modules, what results in error:
ImportError: No module named 'django_app.apps.AppConfig'; 'django_app.apps' is not a package

Django documentation: https://docs.djangoproject.com/en/dev/ref/applications/

**Comment by riklaunim** [comment]
When a new version with this fix will be released?

**Comment by jgoclawski** [comment]
I'd like to see the new version on PyPi as well.
