### ISSUE TITLE
Add support for django 1.8

### ISSUE THREAD

**Issue by chrisdrackett** [miracle2k/django-assets#52]
When running `./manage.py assets build` you get the error `ImportError: cannot import name LaxOptionParser`. This seems to have been removed:

https://github.com/django/django/commit/856863860352aa1f0288e6c9168a0e423c4f5184

**Comment by nostalgiaz** [comment]
+1

**Comment by martino** [comment]
+1

**Comment by polosatyi** [comment]
+ 1

**Comment by gregplaysguitar** [comment]
Any chance of a release incorporating this change? At the moment I can't run assets build on any sites...

**Comment by gregplaysguitar** [comment]
(If there's other issues blocking a release, I'd be happy to help if I can)
