### ISSUE TITLE
New release with Django 1.8 compatibility commits needed

### ISSUE THREAD

**Issue by riklaunim** [miracle2k/django-assets#54]
I would be nice to have a new releases that has all the Django 1.8 compatibility changes.

**Comment by miracle2k** [comment]
For a new set of releases, follow https://github.com/miracle2k/webassets/issues/386

**Comment by psyonara** [comment]
Please, I desperately need to upgrade to Django 1.8 as soon as possible. Even if django-assets gets just a minor version bump to include Django 1.8 compatibility? I would appreciate it immensely.

**Comment by psyonara** [comment]
I guess I can also get it form master for the time being. :-)
