### ISSUE TITLE
Django 1.9 compatibility warning.

### ISSUE THREAD

**Issue by riklaunim** [miracle2k/django-assets#55]
RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9. -- and django-assets imports it.

**Comment by theeluwin** [comment]
See https://github.com/miracle2k/django-assets/commit/c7517b78a385c427500a0f9240d2945ef27dbf1f
This is not applied to current release version https://github.com/miracle2k/django-assets/releases/tag/0.10
You can either ignore warning messages or just use `django-assets` with recent commit-ed version.

**Comment by miracle2k** [comment]
I hop a new release will be out soon.

**Comment by riklaunim** [comment]
requires_model_validation is also deprecated ;)
