### ISSUE TITLE
Compiled assets not added to Django's staticfile manifest

### ISSUE THREAD

**Issue by longhotsummer** [miracle2k/django-assets#56]
I run `collectstatic` and then `build assets` to compile and version my assets in production (webassets does the versioning). I use Whitenoise to serve production assets and (in theory) ensure far-future expire headers for fingerprinted assets.

However, Whitenoise doesn't think the compiled, versioned assets should have an far-futures expired header set because they aren't in the staticfiles.json manifest.

If I run `collectstatic` again after `build assets` it fingerprints the already fingerprinted files.

Is there a way we can solve this or work around it?

Key parts of my settings.py:

```python
STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'
```

In assets.py:

```python
from django_assets import Bundle, register

register('css', Bundle(
    # list 3rd party and raw css here
    'bower_components/fontawesome/css/font-awesome.css',
    Bundle(
        # list SCSS files here
        'stylesheets/app.scss',
        filters='pyscss',
        output='css/styles.%(version)s.css'),
    filters='cssrewrite',
    output='css/app.%(version)s.css'))
```

**Comment by miracle2k** [comment]
Not being up to date with Django, this is the first time I hear about ``staticfiles.json``.

I have two ideas:

- Whitenoise could support the webassets manifest file, in the same way that it supports Django's.

- django-assets, being perfectly aware that it's "build" step complements with "collectstatic", could add the files it generates to ``staticfiles.json``.

**Comment by longhotsummer** [comment]
My vote is for django-assets being aware enough to add entries to staticfiles.json. Does the webassets builder return the output filenames for what it has compiled?

**Comment by miracle2k** [comment]
I'm sure there is some way to get at the info. The right place would probably be an overwritten version of the "build" command.
