### ISSUE TITLE
New package version based on the current master

### ISSUE THREAD

**Issue by edevil** [miracle2k/django-assets#92]
The current master contains some important fixes. It would be great to be able to reference a released version on our requirements.txt files instead of git commits.

Thanks.

**Comment by qwenger** [comment]
poke @miracle2k ?

It'd be really nice to have the latest features (cache file mode, etc.) on pypi... as well as to resolve the mismatch between the features and version advertised in the documentation (which contains the latest features but mentions 0.12 as the current version...)

The same applies for webassets as well, BTW.

Thanks!
